User/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterUserView.as_view(), name='register_page'),
    path('resetpass/<active_code>', views.ResetPasswordView.as_view(), name='reset_pass_page'),
    path('active_user/<email_active_code>', views.ActiveUserView.as_view(), name='active_user_page'),
    path('login/', views.LoginUserView.as_view(), name='login_page'),
    path('forget-pass/', views.ForgotPasswordView.as_view(), name='forgot_pass_page'),
    path('logout/', views.LogOutView.as_view(), name='logout_page'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from site_setting.views import custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('order/',include('order_list.urls')),
    path('article/',include('article.urls')),
    path('',include('contactus_aboutus.urls')),
    path('product/',include('products.urls')),
    path('user/',include('User.urls')),
    path('user-panel/',include('user_panel.urls')),
    path('',include('site_setting.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = custom_404_view

user_panel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('user-basket',views.user_basket, name='user_basket_page'),
    path('user-panel',views.user_dashboard, name='user_dashboard_page'),
    path('user-panel-change-informations',views.user_change_informations.as_view(), name='user_change_informations'),
    path('user-panel-change-password',views.change_user_password.as_view(), name='user_change_password'),
    path('remove-order-detail',views.user_basket_content, name='remove_order_detail'),
    path('change-order-detail',views.change_basket_content_count, name='change_order_detail'),
    path('way-to-pay',views.way2pay, name='way2pay'),
    path('final-payment',views.finalPaymentForm_View.as_view(), name='final_payment'),
    path('faktor-component',views.faktor_component, name='faktor_component'),
    path('pay-card-to-card',views.pay_card_to_card, name='card_to_card_page'),
]

products/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from User.models import User


class Product_Category(models.Model):
    category = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True
                                 , verbose_name='دسته بندی والد ')
    title = models.CharField(max_length=200, verbose_name='اسم دسته بندی', db_index=True)
    url_title = models.CharField(max_length=200, verbose_name='اسم دسته بندی در url', db_index=True, blank=True,
                                 unique=True)
    is_active = models.BooleanField(default=False, verbose_name='فعال/غیرفعال')

    is_delete = models.BooleanField(default=False, verbose_name='موجود/حذف شده')
    image = models.ImageField(upload_to='products/categories/category', null=True, blank=True,
                              verbose_name='عکس دسته بندی')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.url_title = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)
        return self.url_title

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'


class Product_Brand(models.Model):
    title = models.CharField(max_length=200, verbose_name='برند', db_index=True)
    brand_url = models.CharField(max_length=300, verbose_name='عنوان در url', db_index=True, blank=True, unique=True)
    is_active = models.BooleanField(default=False, verbose_name='فعال/غیرفعال')
    image = models.ImageField(upload_to='products/categories/brands', null=True, blank=True, verbose_name='تصویر برند')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.brand_url = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)
        return self.brand_url

    class Meta:
        verbose_name = 'برند'
        verbose_name_plural = 'برندها'


class ProductCars(models.Model):
    title = models.CharField(max_length=100, db_index=True, verbose_name='اسم خودرو')
    url_title = models.CharField(max_length=200, db_index=True, verbose_name='عنوان در url', blank=True, unique=True)
    car = models.ForeignKey('self', verbose_name='دسته بندی والد', on_delete=models.CASCADE,
                            null=True, blank=True)
    logo = models.ImageField(upload_to='cars/image', null=True, blank=True, verbose_name='لوگو خودرو')
    is_active = models.BooleanField(default=True, verbose_name='فعال/غیر فعال')

    class Meta:
        verbose_name = 'خودرو '
        verbose_name_plural = ' خودرو ها'

    def save(self, *args, **kwargs):
        self.url_title = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)
        return self.url_title

    def get_car(self):
        return self.car.title if self.car else None

    get_car.short_description = 'دسته بندی'

    def __str__(self):
        return self.title


class Product_color(models.Model):
    title = models.CharField(max_length=100, verbose_name='نام رنگ')
    url_title = models.CharField(max_length=200, verbose_name='عنوان در url', db_index=True, unique=True,blank=True)
    hex_value = models.CharField(max_length=20, verbose_name='کد رنگ')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.url_title = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)
        return self.url_title

    class Meta:
        verbose_name = 'رنگ محصولات'
        verbose_name_plural = 'رنگ های محصولات'


class suggestion(models.Model):
    title = models.CharField(max_length=100, verbose_name='محل نصب', db_index=True)

    class Meta:
        verbose_name = 'محل نصب قطعه'
        verbose_name_plural = 'محل نصب قطعات'

    def __str__(self):
        return self.title


class Products(models.Model):
    class Position(models.TextChoices):
        front = 'front', "جلو"
        right_front = 'right_front', "جلو راست و جلو چپ"
        right = 'right', " راست"
        left = 'left', "چپ"
        back = 'back', 'عقب'
        right_back = 'right_back', "عقب راست و عقب چپ"

    class Material(models.TextChoices):
        plastic = 'plastic', 'پلی اتیلن'
        felez = 'felez', 'فلز'
        glass = 'glass', 'شیشه'
        poly_carbonat = 'poly_carbonat', 'پلی کربنات (پلاستیک Uv)'

    class garanti(models.TextChoices):
        zemanat_none = 'zemanat_none', 'فاقد ضمانت از سمت تولید کننده میباشد'
        zemanat_1_sale = 'zemanat_1_sale', 'دارای 1 سال ضمانت رنگ میباشد'
        zemanat_5_sale = 'zemanat_5_sale', 'دارای 5 سال ضمانت رنگ میباشد'

    title = models.CharField(max_length=200, verbose_name='اسم محصول')
    short_description = models.TextField(verbose_name='توضیحات کوتاه', db_index=True)
    description = models.TextField(verbose_name='توضیحات کامل')
    price = models.IntegerField(verbose_name='قیمت')
    is_active = models.BooleanField(default=False, verbose_name='فعال/غیرفعال')
    car_products = models.ForeignKey(ProductCars, null=True, verbose_name='خودرو', db_index=True,
                                     on_delete=models.CASCADE)
    brand = models.ForeignKey(Product_Brand, null=True, db_index=True, verbose_name='برند ها', on_delete=models.CASCADE)
    Category = models.ManyToManyField(Product_Category, db_index=True, verbose_name='دسته بندی محصول')
    has_color = models.BooleanField(verbose_name='محصول دارای رنگ بندی است ؟', db_index=True, default=False)
    colors = models.ManyToManyField(Product_color, db_index=True, verbose_name="رنگ های محصول", blank=True)
    position = models.CharField(max_length=200, choices=Position.choices, verbose_name="محل نصب", null=True)
    side = models.BooleanField(default=False, verbose_name='آیا قطعه دارای جهت بندی میباشد')
    suggest = models.ManyToManyField(suggestion, verbose_name='ایجاد ارتباط برای پیشنهاد', blank=True, db_index=True)
    material = models.CharField(max_length=200, choices=Material.choices, verbose_name="جنس", null=True)
    garanti = models.CharField(max_length=200, choices=garanti.choices, verbose_name='وضعیت ضمانت', null=True)
    cars = models.CharField(max_length=500, verbose_name='مناسب برای خودرو', null=True, db_index=True)
    slug = models.SlugField(db_index=True, null=False, blank=True, allow_unicode=True, verbose_name='اسلاگ')
    image = models.ImageField(upload_to='images/uploads/', null=True, blank=True, verbose_name='تصویر محصول')
    is_delete = models.BooleanField(default=False, verbose_name='موجود/حذف شده')

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = "محصولات"

    def get_absolute_url(self):
        return reverse('products_detail_page', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)
        return self.slug

    def __str__(self):
        return self.title


class PriceByProductColor(models.Model):
    products = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول', db_index=True)
    colors = models.ManyToManyField(Product_color, verbose_name="رنگ ها")
    price_by_color = models.IntegerField(verbose_name='قیمت محصول بر اساس رنگ')

    def __str__(self):
        color_names = ', '.join([color.title for color in self.colors.all()])
        return f"{self.products} | رنگ ها : {color_names} | {self.price_by_color}"

    class Meta:
        verbose_name = 'قیمت محصول بر اساس رنگ'
        verbose_name_plural = "قیمت محصولات بر اساس رنگ ها "




class ProductVisited(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='کالا')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name='کاربر')
    ip = models.CharField(max_length=30, verbose_name='ip کاربر')

    class Meta:
        verbose_name = 'بازدید محصول'
        verbose_name_plural = 'بازدید های محصولات'

    def __str__(self):
        return f"{self.product.title} / {self.user}"


class ProductGallery(models.Model):
    products = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول')
    images = models.ImageField(upload_to='images/galleries', verbose_name='تصاویر محصول')

    def __str__(self):
        return self.products.title

    class Meta:
        verbose_name = 'تصویر گالری'
        verbose_name_plural = 'گالری تصاویر'


class ProductComment(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name="محصول")
    parent = models.ForeignKey('self', on_delete=models.CASCADE, verbose_name='والد', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')
    text = models.TextField(verbose_name='متن نظر')
    is_active = models.BooleanField(default=False, verbose_name='نمایش داده شود/ نشود')

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'نظر محصول'
        verbose_name_plural = 'نظرات محصولات'

user_panel/forms.py
from User.models import User
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from order_list.models import final_payment

class ChangeUserInformationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'avatar', 'address', 'about_user']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control',
                                          'placeholder': 'نام'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control',
                                          'placeholder': ' نام خانوادگی'}),
            'username': forms.TextInput(attrs={'class': 'form-control',
                                          'placeholder': ' نام کاربری'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control',
                                          'placeholder': 'تصویر پروفایل'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 3,
                                             'id': 'message',
                                          'placeholder': 'آدرس'}),
            'about_user': forms.Textarea(attrs={'class': 'form-control', 'rows': 6,
                                                'id': 'message',
                                          'placeholder': 'درباره شما'}),
        }
        labels = {
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'avatar': 'تصویر پروفایل',
            'address': 'آدرس',
            'about_user': 'درباره شخص',
        }


class user_change_passwordForm(forms.Form):
    current_password = forms.CharField(
        label='کلمه عبور فعلی شما',
        widget=forms.PasswordInput(attrs={'class': 'inp',
                                          'placeholder': ' کلمه عبور فعلی'}),
        validators=[
            validators.MaxLengthValidator(100),
        ]
    )
    password = forms.CharField(
        label='کلمه عبور جدید',
        widget=forms.PasswordInput(attrs={'class': 'inp',
                                          'placeholder': ' کلمه عبور جدید'}),
        validators=[
            validators.MaxLengthValidator(100),
        ]
    )
    confirm_password = forms.CharField(
        label='تکرار کلمه عبور',
        widget=forms.PasswordInput(attrs={'class': 'inp',
                                          'placeholder': 'تکرار کلمه عبور جدید'}),
        validators=[
            validators.MaxLengthValidator(100)
        ]
    )

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if confirm_password == password:
            return confirm_password
        raise ValidationError('تکرار کلمه عبور شما با کلمه عبور شما مغایرت دارد')



class final_payment_Form(forms.ModelForm):
    class Meta:
        model = final_payment
        fields = '__all__'
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control','placeholder':'استان شهرستان و محل تحویل', 'rows': 3}),
            'postal_code': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 2,}),
        }

user_panel/templates/user_basket/user_basket.html
{% extends 'lay_out/layout.html' %}
{% load poll_extras %}
{% block title %}سبد خرید شما{% endblock %}
{% block content %}
    <div id="order_detail_content">
        {% include 'user_basket/user_basket_content.html' %}
    </div>
{% endblock %}

user_panel/templates/user_basket/user_basket_content.html
{% load poll_extras %}

{% if order_details %}
    <section id="cart_items">
        <div class="container" id="cart_container">
            {% for detail in order_details %}
                <div class="cart_container">
                    <div class="cart_informations">
                        <div class="cart_info">
                            <a href="{{ detail.order.products.get_absolute_url }}"
                               id="cart_product_title">{{ detail.order.products.title }}</a>
                            <div class="basket_product_color_container">
                                {% if detail.color %}
                                    <p class="basket_product_text">رنگ : {{ detail.color }}</p>
                                    <span class="basket_product_color"
                                          style="background-color: {{ detail.color.hex_value }};"></span>
                                {% else %}
                                {% endif %}
                                {% if detail.order.side %}
                                    <p class="basket_product_text">سمت : {{ detail.order.get_side_display }}</p>
                                {% else %}
                                {% endif %}

                            </div>
                            <h5 class="garanti fa fa-check-circle " id="g"> گارانتی اصالت و سلامت فیزیکی
                                کالا </h5>
                            <h5 id="garanti">ضمانت : {{ detail.order.products.get_garanti_display }} </h5>
                            <div>
                                <h3 id="cart_total_price_mobile">قیمت نهایی
                                    : {{ detail.order_total_price | int_comma }}</h3>
                            </div>
                        </div>
                        <h4 class="cart_price">قیمت واحد : {{ detail.price | int_comma }}</h4>
                        <a href="{{ detail.order.products.get_absolute_url }}"><img
                                src="{{ detail.order.products.image.url }}" alt="" class="cart_image"></a>


                    </div>
                    <div class="cart_footer">
                        <div class="cart_quantity_button">
                            <h3>تعداد : </h3>
                            <a class="cart_quantity_up"
                               onclick="changeOrderDetail({{ detail.order.id }}, 'increase')">
                                + </a>
                            <input class="cart_quantity_input" type="text" name="quantity"
                                   value="{{ detail.order.count }}" autocomplete="off" size="2">
                            <a class="cart_quantity_down"
                               onclick="changeOrderDetail({{ detail.order.id }}, 'decrease')"> - </a>
                        </div>
                        <div>
                            <h3 class="cart_total_price" id="cart_total_price_pc">قیمت نهایی
                                : {{ detail.order_total_price | int_comma }}</h3>
                        </div>
                        <div>
                            <a class="cart_quantity_delete"
                               onclick="removeOrderDetail({{ detail.order.id }})"><i
                                    class="fa fa-times"></i></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <span id="q_and_answer_link"> <img src="/static/images/blog/q_&_a.png"> <a
                    href="{% url 'q_and_answer_view' %}"> پرسش و پاسخ های متداول </a></span>
        </div>
    </section>
    <section id="do_action">
        <div class="container">
            <div class="row">
                <div class="way2pay">
                    <a href="{% url 'way2pay' %}"><h2>اطلاع از روش های پرداخت </h2></a>
                </div>
                <div class="way2pay-mobile">
                    <a href="{% url 'way2pay' %}"><h2>اطلاع از روش های پرداخت </h2></a>
                </div>
                <div class="col-sm-4">
                    <div class="total_area">
                        <div id="total_area_pc">
                            <h3>صورت حساب شما</h3>
                            <ul>
                                {% for detail in order_details %}
                                    <li>{{ detail.order.products.title }}{% if detail.color %} رنگ : {{ detail.color }}{% endif %}<span>{{ detail.price | int_comma }}</span></li>
                                {% endfor %}
                                <li id="li"><h4>مجمـوع :</h4>  {{ total_price | int_comma }}</li>
                            </ul>
                            <a class="btn btn-default check_out" href="{% url 'final_payment' %}">ادامه خرید</a>
                        </div>
                        <div id="total_area_mobile"><a class="btn btn-default check_out"
                                                       href="{% url 'final_payment' %}"> {{ total_price | int_comma }} | ادامه
                            خرید </a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% else %}
    <div class="container">
        <div class="empty-basket">
            <img src="/static/images/cart/empty-basket.png" alt="">
            <a href="{% url 'products_list_page' %}"><h2>مشاهده لیست قطعات </h2></a>
            <div class="alert alert-warning">
                <h2>سبد خرید شما خالی است</h2>
            </div>
        </div>
    </div>
{% endif %}